CREATE DATABASE TEMP;
USE TEMP;
CREATE TABLE CUSTOMER (
	CUST_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CNMAE VARCHAR(225),
    ADDRESS VARCHAR(225),
    GENDER CHAR(2),
    CITY VARCHAR(225),
    PINCODE INTEGER
);

INSERT INTO CUSTOMER 
VALUES (1251, 'RAM KUMAR', 'DILBAGH NAGAR', 'M', 'JALANDAR', 144002), 
(1300, 'SHYAM SINGH', 'LUDHINIA H.O', 'M', 'LUDHIANA', 141001), 
(1301, 'ARTI DEVI', 'GT KARNAL ROAD', 'F', 'DELHI', 110075);

INSERT INTO CUSTOMER 
VALUES (1242, 'RAMKUMAR IMPOSTER', 'AFDFS', 'M', 'AFDFA', NULL);

CREATE TABLE ORDER_TABLE (
	ORDER_ID INTEGER PRIMARY KEY,
    DELIVERY_DATE DATE,
    ID INT,
    FOREIGN KEY(ID) REFERENCES CUSTOMER(CUST_ID)
);

DROP TABLE ORDER_TABLE;
CREATE TABLE ORDER_TABLE (
	ORDER_ID INTEGER PRIMARY KEY,
    DELIVERY_DATE DATE,
    CUST_ID INT,
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

INSERT INTO ORDER_TABLE
VALUES (1, '2019-03-11', 1301);


-- UNIQUE CONSTRAINT
-- MATLAB JAISE FIRST NAME UNIQUE HONA CHAIYE
/*

CRATE TABLE X (
	NAME VARCHAR(225) UNIQUE, ....
);
*/

-- CHECK :: CONSISTENCY CONSTRAINT 

/*
CREATE TABLE ACCOUNT(
	CONSTRAINT ACCOUNT_BALANCE CHECK(ACCOUNT_BALANCE > 1000),
    -- TO MATLAB AB AGAR MEIN ADD KAR RAHA TOH VOH <=1000 VALA REJECT MAR DEGA
);
*/

CREATE TABLE ACCOUNT_INFO(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE,
    BALANCE INT,
    CONSTRAINT ACC_BALANCE_CHK CHECK(BALANCE > 1000)
);


INSERT INTO ACCOUNT_INFO 
VALUES (1, 'RAM KUMAR', 1400);

INSERT INTO ACCOUNT_INFO
VALUE(2, 'RAM KUMAR', 23479); -- GIVES AN ERROR DUPLICATE ENTRY 'RAM KUMAR' FOR KEY 'ACCOUNT_INFO.NAME'

INSERT INTO ACCOUNT_INFO VALUE(2, 'RAM SHYAM', 18); -- CHECK CONSTRAINT ACC_BALANCE_CHK IS VIOLATED


-- DEFAULT CONSTRAINT

DROP TABLE ACCOUNT_INFO;
CREATE TABLE ACCOUNT_INFO(
	ID INT PRIMARY KEY,
    NAME VARCHAR(225) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0
);

INSERT INTO ACCOUNT_INFO VALUES(1, 'RAM KUMAR', 10000);

INSERT INTO ACCOUNT_INFO(ID, NAME) VALUES(2, 'B'); -- ISME AUTOMATICALLY ISKA BALANCE 0 SET HO JAYEGA [NAYA ACCOUNT BANAYA]
-- JAISE BY DEFAULT AGAR NAYA BANDA ACCOUNT BANA USKA LOAN =  0
SELECT * FROM ACCOUNT_INFO;


-- AN ATTRIBUTE CAN BE PRIMARY KEY AND FOREIGN KEY

-- ALTERING OPERATIONS
-- ADD MODIFY CHANGE DROP RENAME

-- ADD NEW COLUMN


ALTER TABLE ACCOUNT_INFO ADD INTEREST FLOAT NOT NULL DEFAULT 0;
SELECT * FROM ACCOUNT_INFO;


-- MODIFY A DATATYPE OF AN ATTRIBUTE 

ALTER TABLE ACCOUNT_INFO MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;

DESC ACCOUNT_INFO; -- DESC SE DESCRIBE KAR SAKTE SARA INFO



-- CHANGE COLUMN-RENAME THE COLUMN


ALTER TABLE ACCOUNT_INFO CHANGE COLUMN INTEREST SAVING_INTEREST FLOAT NOT NULL DEFAULT 0;

-- DROP COLUMN

ALTER TABLE ACCOUNT_INFO DROP COLUMN SAVING_INTEREST;

-- RENAME THE TABLE 

ALTER TABLE ACCOUNT_INFO RENAME TO ACCOUNT_DET;
SELECT * FROM ACCOUNT_DET;


-- dml INSERT UPDATE DELETE REPLACE


SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER(CUST_ID, CNMAE, ADDRESS, GENDER, CITY, PINCODE)
VALUES (1456, 'YO', 'RWEF', 'M', 'DFKSAF', 10101);


INSERT INTO CUSTOMER(CUST_ID, CNMAE) VALUES(12314, 'FDASJF');


-- UPDATE
UPDATE CUSTOMER SET ADDRESS = 'MUMBAI', GENDER = 'M' WHERE CUST_ID = 12314;

-- UPDATING MULTIPLE ROWS
-- SET SQL_SAFE_UPDATES = 0;
UPDATE CUSTOMER SET PINCODE = 11000;

UPDATE  CUSTOMER SET PINCODE = PINCODE + 1;


-- DELETE COMMAND

DELETE FROM CUSTOMER WHERE CUST_ID = 1456;
SELECT * FROM CUSTOMER;

-- SAB KO UDANA HO 
-- SET SQL_SAFE_UPDATE = 0
-- DELETE FROM CUSTOMER



-- ON DELETE CASCADE 
-- ON DELETE SET NULL

SELECT * FROM ORDER_TABLE;
SELECT * FROM CUSTOMER;

DELETE FROM CUSTOMER WHERE CUST_ID = 1301; -- CANNOT DELETE THIS WAY!!

DROP TABLE ORDER_TABLE;

CREATE TABLE ORDER_TABLE (
	ORDER_ID INTEGER PRIMARY KEY,
    DELIVERY_DATE DATE,
    CUST_ID INT,
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE
);

INSERT INTO ORDER_TABLE VALUES(1, '2002-10-10', 1301);

DELETE FROM CUSTOMER WHERE CUST_ID = 1301; -- NOW IT WILL BE DELTED

-- REPLACE

-- DATA ALREADY PRESENT -> REPLACE
-- DATA NOT PRESENT -> TOH PHIR YE INSERT KI TARAH BEHAVE KAREGA

-- SAB KUCH JO GIVEN KARA VO SET KARDEGA BAKI SAB NULL KARDEGA
REPLACE INTO CUSTOMER(CUST_ID, CITY) VALUES (1241, 'DELHI');
SELECT * FROM CUSTOMER;
 
-- AGAR VO VLAUE PRESENT 
REPLACE INTO CUSTOMER(CUST_ID, CNMAE, ADDRESS, GENDER, CITY, PINCODE)
VALUES (1234, 'AFDSFAS', 'FADSFAS', 'F', 'FASDF', 101010); 
-- YE SAB INSERT HO GAYA

-- JO JO VALUE DI USKE ALAVA SAB NULL SET HO JAYEGA
REPLACE INTO CUSTOMER(CUST_ID, CNMAE, CITY)
	SELECT CUST_ID, CNMAE, CITY
    FROM CUSTOMER WHERE CUST_ID = 1242;
    
-- REPLACE VS UPDATE 
-- DATA ALREADY (UPDATE), NOT THERE(INSERT) ||| PAR UPDATE WILL ONLY UPDATE WON'T ADD IF NO DATA








