USE JOINS_;

-- SUBQUERIES
-- WHERE CLAUSE SAME TABLES 
-- EMPLOYESS WITH AGE > 30

SELECT * FROM EMPLOYEE WHERE AGE IN (SELECT AGE FROM EMPLOYEE WHERE AGE > 30);

-- WHERE CLAUSE IN DIFFERENT TABLE
-- EMP DETAILS WORKING IN MORE THAN 1 PROJECT.
SELECT * FROM EMPLOYEE WHERE ID IN (
	SELECT EMP_ID FROM PROJECT GROUP BY EMP_ID HAVING COUNT(EMP_ID) > 1
);

-- SINGLE VALUE SUBQUERIES
-- EMP DETAILS HAVING AGE > AVG AGE

SELECT * FROM EMPLOYEE WHERE AGE > (SELECT AVG(AGE) FROM EMPLOYEE);

-- FROM CLAUSE -- DERIVED TABLE
-- SELECT MAX AGE PERSON WHOSE FIRST NAME CONTAINS 'A'

SELECT MAX(AGE) FROM (SELECT * FROM EMPLOYEE WHERE FNAME LIKE '%A%') AS TEMP;

-- CORELATED SUBQUERY

-- FIND 3RD OLDEST EMPLOYEE

SELECT *
FROM EMPLOYEE AS E1
WHERE 3 = (

	SELECT COUNT(E2.AGE) FROM EMPLOYEE AS E2 
    WHERE E2.AGE >= E1.AGE
);
